version: '3.9'
services:
  service-mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=upesi
      - MARIADB_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      - MARIADB_USER=upesi
      - MARIADB_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3308:3306'
  service-redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - "./data/redis:/data/redis"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    environment:
      - REDIS_REPLICATION_MODE=master
  service-upesi-auth:
    image: service-upesi-auth:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: upesi-auth-server/Dockerfile
      cache_from:
        - alpine:3.10.2
        - openjdk:17.0.1-jdk-slim
        - maven:3.8.7-openjdk-18-slim
    ports:
      - target: 9000
        published: 9000
    volumes:
        - "${HOME}/.m2:/root/.m2"
    depends_on:
      - service-mariadb
      - service-redis
    environment:
      - DATABASE_URL=r2dbc:mariadb://service-mariadb:3306/upesi?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false
      - LIQUIBASE_DATABASE_URL=jdbc:mariadb://service-mariadb:3306/upesi?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false
      - DATABASE_NAME=upesi
      - DATABASE_USER=upesi
      - DATABASE_PASSWORD=mauFJcuf5dhRMQrjj
      - CONNECTION_POOL_ENABLED=true
      - CONNECTION_POOL_INITIAL_SIZE=10
      - MIN_POOL_SIZE=3
      - MAX_POOL_SIZE=20
      - VALIDATION_DEPTH=local
      - VALIDATION_QUERY=SELECT 1
      - MAX_IDLE_TIME=3m
      - HASH_FUNCTION=SHA3-256
      - LOG_PATH=/var/log/
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    external_links:
      - service-mysql
      - service-redis
      - localstack
    restart: on-failure
  # service-upesi-account:
  #   image: service-upesi-account:latest
  #   platform: linux/amd64
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     cache_from:
  #       - alpine:3.10.2
  #       - openjdk:17.0.1-jdk-slim
  #       - maven:3.8.7-openjdk-18-slim
  #   ports:
  #     - target: 9080
  #       published: 9080
  #   volumes:
  #       - "${HOME}/.m2:/root/.m2"
  #   depends_on:
  #     - service-mariadb
  #     - service-redis
  #   environment:
  #     - DATABASE_URL=r2dbc:mariadb://service-mariadb:3306/upesi?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false
  #     - LIQUIBASE_DATABASE_URL=jdbc:mariadb://service-mariadb:3306/upesi?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false
  #     - DATABASE_NAME=upesi
  #     - DATABASE_USER=upesi
  #     - DATABASE_PASSWORD=mauFJcuf5dhRMQrjj
  #     - CONNECTION_POOL_ENABLED=true
  #     - CONNECTION_POOL_INITIAL_SIZE=10
  #     - MIN_POOL_SIZE=3
  #     - MAX_POOL_SIZE=20
  #     - VALIDATION_DEPTH=local
  #     - VALIDATION_QUERY=SELECT 1
  #     - MAX_IDLE_TIME=3m
  #     - HASH_FUNCTION=SHA3-256
  #     - LOG_PATH=/var/log/
  #     - LOG_LEVEL=DEBUG
  #     - REDIS_HOST=127.0.0.1
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
# Names our volume
volumes:
  cache:
    driver: local
  upesi: