server:
  port: 9000
  servlet:
    context-path: /v1
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 1000
      worker: 5000
spring:
  application:
    name: auth-server
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    r2dbc:
      url: ${DATABASE_URL:r2dbc:mariadb://service-mariadb:3306/upesi?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false}
      username: ${DATABASE_USER:transactions}
      password: ${DATABASE_PASSWORD:mauFJcuf5dhRMQrjj}
      pool:
        enabled: ${CONNECTION_POOL_ENABLED:true}
        initial-size: ${CONNECTION_POOL_INITIAL_SIZE:10}
        min-idle: ${MIN_POOL_SIZE:3}
        max-size: ${MAX_POOL_SIZE:20}
        validation-depth: ${VALIDATION_DEPTH:local}
        validation-query: ${VALIDATION_QUERY:SELECT 1}
        max-idle-time: ${MAX_IDLE_TIME:3m}

    datasource:
      url: ${DATABASE_URL:r2dbc:mariadb://service-mariadb:3306/upesi?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false}
      driverClassName: org.mariadb.jdbc.Driver
      username: ${DATABASE_USER:transactions}
      password: ${DATABASE_PASSWORD:mauFJcuf5dhRMQrjj}

    liquibase:
      change-log: db/migration/db-changelog.yaml
      default-schema: ${DATABASE_NAME:finance-transactions}
      user: root
      password: ${DATABASE_PASSWORD:mauFJcuf5dhRMQrjj}
      parameters:
        textColumnType: TEXT
      url: ${LIQUIBASE_DATABASE_URL:jdbc:mariadb://service-mariadb:3306/upesi?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false}
    sql:
      init:
        mode: always
        continue-on-error: false
    cloud:
      config:
        enabled: false
    data:
      redis:
        host: ${REDIS_HOST:127.0.0.1}
        port: ${REDIS_PORT:6379}
        password: ${REDIS_PASSWORD:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81}
    cache:
      type: redis

  logging:
    level:
      "com.upesi": ${LOG_LEVEL:DEBUG}
      "liquibase": info
    file:
      path: ${LOG_PATH:/tmp/auth-service/}

  management:
    endpoint:
      health:
        enabled: true

  security:
    hash: ${HASH_FUNCTION:SHA3-256}